either:
    - "#indonesiagelap"
    - "#peringatandarurat"
    - "#tolakrevisiuutni"
    - "#tolakdwifungsiabri"
    - "#tolakruupolri"
    - "#supremasisipil"
    - "#cabutruutni"
    - "#tolakruutni"
    - "#cabutuutni"
    - "#gagalkanruutni"
    - "#gagalkanuutni"
    - "ruu tni"
    - "#tolakruukejaksaan"
    - "#kembalikantnikebarak"
    - "dwifungsi"
    - "dwifungsi abri"
    - "uu tni"
until: "2025-05-30"
scroll_timeout: 20000
scroll_delay: 1000
